package VORLESUNG.W03.D04

fun main(){
    var list = mutableListOf(1,2,3,4,5,6,7,8,9)
    println("Der Unterschied zwischen \".shuffled()\" und \".shuffle()\" ")
    println("Erstmal shuffled")
    readln()
    println(list.shuffled())
    println(list)
    println("Die ursprüngliche Liste wird nicht verändert")
    readln() //damit man mit Enter in der Console weiter kann und sich dabei den Code anschauen kann
    println("")
    println("Jetzt das selbe mit \".shuffle()\"")
    println(list.shuffle())
    println(list)
    println("shuffle hat ein anderes return und alleine der Aufruf verändert schon die Liste\n" +
            "auch wenn man es in eine andere Variable speichert")
    readln()
    println("")
    println("Deshalb muss man aufpassen")
    println("Ich lege die Liste jetzt nochmal neu an")
    list = mutableListOf(1,2,3,4,5,6,7,8,9)
    println("list: " +list)
    readln()
    println("")
    println("und speichere sie jetz in eine neue Liste")
    println("erst mit shuffled:")
    readln()
    var newList = list.shuffled().toMutableList()
    println("list: " +list)
    println("newList: " + newList)
    readln()
    println("")
    println("Jetzt das ganze mit \".shuffle()\"")
    println("Da shuffle ja nur \"kotlin.Unit\" returned, speichere einfach\n"+
            "erstmal in der neuen Liste die erste Liste ab und verwende dann shuffle")
    readln()
    println("")
    list = mutableListOf(1,2,3,4,5,6,7,8,9)
    var superNewList = list
    superNewList.shuffle()
    println("list: "+list)
    println("superNewList: "+superNewList)
    readln()
    println("")
    println("Die Zeile \"var superNewList = list\" verknüpft beide Listen miteinander")
    println("So etwas heisst: \"Call-By-Reference\"")
    println("Der Name ist nicht so wichtig, sondern die Wirkung")
    Thread.sleep(3000)
    println("Alles was ich jetzt in einen der beiden Listen mache, hat Auswirkung auf die andere")
    list.removeAt(0)
    println("")
    println(list)
    println(superNewList)
    superNewList.add(3)
    println(list)
    println(superNewList)
    readln()
    println("")
    println("Da die kotlin-Programmierer aber auch nicht dumm waren\n" +
            "und sich ein bisschen etwas gedacht haben, gilt das auch für\n" +
            ".sort() und sorted(), .reverse() und .reversed(), etc")
}